### ISSUE TITLE
Support for new API

### ISSUE THREAD

**Issue by BassemN** [CakeDC/recaptcha#42]
Hi,
Does this plugin support the new reCAPTCHA API https://developers.google.com/recaptcha/docs/display#auto_render ?
Thanks

**Comment by angelxmoreno** [comment]
:+1:

**Comment by jamespayne** [comment]
Yes... I would like to see this too.

**Comment by blueangelcpt** [comment]
+1

**Comment by steinkel** [comment]
Fixed in v3.0.0
