### ISSUE TITLE
Undefined property: ToolbarAccess::$Behaviors

### ISSUE THREAD

**Issue by BassemN** [CakeDC/recaptcha#43]
Hi,
I'm using DebugKit.Toolbar, When I click on "Explain" button I got the below error
![undefined propert](https://cloud.githubusercontent.com/assets/3768012/5145905/beb8c1a6-71af-11e4-8334-f3a40fdc54aa.jpg)
Please advise

Thanks

**Comment by steinkel** [comment]
Fixed in v3.0.0
