### ISSUE TITLE
error on adding component

### ISSUE THREAD

**Issue by chhabegrex** [CakeDC/recaptcha#51]
syntax error, unexpected '['

Php version 5.3.3
cake 2.7

**Comment by jaycenet** [comment]
Simply modify this on line 130 in RecaptchaComponent.php :
        $this->Controller->{$modelClass}->Behaviors->load('Recaptcha.Recaptcha', array(
            'field' => $errorField,
        ));

**Comment by andrej-griniuk** [comment]
That was the only incompatibility with PHP 5.3
Solved and merged to develop.

**Comment by ghost** [comment]
This still not in master.. only develop
