### ISSUE TITLE
RecaptchaComponent::display()

### ISSUE THREAD

**Issue by mackieg** [CakeDC/recaptcha#53]
Using CakePHP 2 on this specific project.
    Downloaded your recaptcha-2.2.4 from Git.
    Copied Controller, Locale, Model & View to app/Plugin/Recaptcha
    Edited bootstrap.php to include:
        publicKey
        privateKey
        loaded 'Recaptcha'
    In my login action added echo $this->Recaptcha->display();

Get an error:
Fatal error: Call to undefined method RecaptchaComponent::display() in app/Controller/UsersController.php on line 38

All line 38 is ...$this->Recaptcha->display();

**Comment by steinkel** [comment]
What means "Copied Controller, Locale, Model & View to app/Plugin/Recaptcha"? the plugin contents should not be modified this way, but used in your application. How did you install the plugin?

**Comment by mackieg** [comment]
Hi Jorge
Thanks for getting back to me. Just didn't want to over explain things.
I copied your app files (unchanged) to my project folder "app/Plugin/Recaptcha".

**Comment by steinkel** [comment]
Did you load the plugin and load the Recaptcha component in your controller?

**Comment by mackieg** [comment]
Yes,
in the file bootstrap.php added: CakePlugin::load('Recaptcha');
in the controller: public $components = array('Recaptcha.Recaptcha');

**Comment by steinkel** [comment]
Ok, we'll try to reproduce this issue in a public environment and get back to you. Thanks,

**Comment by mackieg** [comment]
I have changed my logic in where it is used and got it to work. Really greatful for your attentions to this.
